language: node_js
sudo: false
node_js:
  - "node"

install:
  - npm install

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - ls -al
  # Startup fake API.
  - node_modules/.bin/json-server --watch test/fixtures/db.json --id=_id --middlewares test/atlas-middleware.js --routes test/routes.json > /dev/null 2>&1 &
  # Change the location the local URL is pointed to.
  - sed -i "149i store.state.atlasEnvironments.Local = 'http://localhost:3000/';" src/vuex/store.js
  # Run tests.
  - npm run e2e

