language: node_js
sudo: false
node_js:
  - "node"

addons:
  # The username and access key are stored in the Travis settings.
  sauce_connect: true

install:
  # Install depedencies.
  - npm install

script:
  
  # Startup fake API.
  - node_modules/.bin/json-server --watch test/fixtures/db.json --id=_id --middlewares test/atlas-middleware.js --routes test/routes.json > /dev/null 2>&1 &
  
  # Run tests.
  # - GH_USER=GITHUB_USER GH_TOKEN=GITHUB_TOKEN npm run e2e
  - npm run e2e
