language: node_js
<<<<<<< HEAD
sudo: false
=======
>>>>>>> 1.x
node_js:
  - "node"

install:
<<<<<<< HEAD
  # Intentionally break tests for now.
  # @todo Add Sauce Connect account.
  - chmod +x foo.txt

  - npm install

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

script:
  - ls -al
  # Startup fake API.
  - node_modules/.bin/json-server --watch test/fixtures/db.json --id=_id --middlewares test/atlas-middleware.js --routes test/routes.json > /dev/null 2>&1 &
  # Test response of API.
  - curl http://localhost:3000/
  # Change the location the local URL is pointed to.
  - sed -i "149i store.state.atlasEnvironments.Local = 'http://localhost:3000/';" src/vuex/store.js
  # Run tests.
  # - npm run e2e
=======
  - npm install

script:
  - node_modules/.bin/json-server --watch test/fixtures/db.json --id=_id --host=atlas.testing --middlewares test/atlas-middleware.js --routes test/routes.json
  - sed -i "149i store.state.atlasEnvironments.Local = 'http://atlas.testing:3000/';" src/vuex/store.js
  - npm run e2e
>>>>>>> 1.x

